config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

 resources :users, only: [:new, :create]
  root 'listings#index'

  resources :listings

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	 mount_uploader(:image, ImageUploader)
	 mount_uploader(:image2, ImageUploader)
	 mount_uploader(:image3, ImageUploader)
	 mount_uploader(:image4, ImageUploader)
	 mount_uploader(:image5, ImageUploader)
	 mount_uploader(:image6, ImageUploader)
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
 def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

    def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_filter :ensure_logged_in, only: [:create, :destroy]
	def index
		@listings = Listing.all
	end

	def show
		@listing = Listing.find(params[:id])
	end

	def new
		@listing = Listing.new
	end

	 def create

    @listing = Listing.new(listing_params)
    if @listing.save

      redirect_to listings_url
    else

      render :new
    end
  end

  def edit
  	@listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])

    if @listing.update_attributes(listing_params)
      redirect_to "/listings/#{@listing.id}"
    else
      render :edit
    end
  end

    def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to listings_url
  end


  private
  def listing_params
    # binding.pry
    params.require(:listing).permit(:address, :city, :agent, 
      :bedrooms, :bathrooms, :price, :sqft, 
      :description, :agent, :website, :email, :number, :image, :image2, :image3,
      :image4, :image5, :image6)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to listings_url, notice: "Logged in!"
  	else
  		  flash.now[:alert] = "Invalid email or password"
  		render "new"
  	end
  end


  def destroy
    session[:user_id] = nil
    redirect_to listings_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to listings_url, notice: "Welcome to ListEasy"
  	else render "new"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ListEasy - The Fastest Way To Single Listings Sites</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,500,300,200,100' rel='stylesheet' type='text/css'>
</head>

<header>

<div class="h-title">
Easylist<span class="h-subtitle">Create A New Listing</span>
</div>
</header>
<div class="page-container">
 <!-- <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p> -->
  <body>
    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

  <%= yield %>


  </body>
</html>

app/views/listings/edit.html.erb
<h1>Edit Listings</h1>

<p><%= link_to "Back", @listing %></p>

<%= form_for @listing do |f| %>
  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :agent %><br>
    <%= f.text_field :agent %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/listings/index.html.erb
<!-- <div class="main-title">

Welcome to ListEasy

</div> -->

<!-- <h1>Listings</h1> -->
<!-- <div class="menu-nav"> -->
<div class="title-info">
<%= link_to "Create New Listing", "/listings/new" %>
</div>
<% @listings.each do |listing| %>
<div class="title-info">
<p><%= listing.address %> | <%= listing.price %> | <%= listing.agent %></p>
 <p><%= link_to image_tag(listing.image.url), "/listings/#{listing.id}" %></p>
</div>

<div class="listing-info">
<p>Check out <%= link_to listing.address, "/listings/#{listing.id}" %></p>
</div>


	 <% end %>

app/views/listings/new.html.erb
<h1>Create New Listing</h1>
<div class="forms">

<%= link_to "Back to Listings", listings_url %>
<%= form_for @listing do |f| %>
  

  <p>
    <%= f.label :Listing_Address %><br>
    <%= f.text_field :address %>
  </p>

    <p>
    <%= f.label :City %><br>
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :agent_name %><br>
    <%= f.text_field :agent %>
  </p>

    <p>
    <%= f.label :agent_website %><br>
    <%= f.text_field :website %>
  </p>

    <p>
    <%= f.label :agent_email %><br>
    <%= f.text_field :email %>
  </p>

    <p>
    <%= f.label :agent_phone_number %><br>
    <%= f.text_field :number %>
  </p>

    <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.label :bathrooms %><br>
    <%= f.text_field :bathrooms %>
  </p>

	  <p>
    <%= f.label :bedrooms %><br>
    <%= f.text_field :bedrooms %>
  </p>

    <p>
    <%= f.label :square_feet %><br>
    <%= f.text_field :sqft %>
  </p>

    <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, :size => "50x10" %>
  </p>

   <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
  
   <p>
    <%= f.label :image2 %><br>
    <%= f.file_field :image2 %>
  </p>
  
    <p>
    <%= f.label :image3 %><br>
    <%= f.file_field :image3 %>
  </p>

    <p>
    <%= f.label :image4 %><br>
    <%= f.file_field :image4 %>
  </p>

    <p>
    <%= f.label :image5 %><br>
    <%= f.file_field :image5 %>
  </p>

    <p>
    <%= f.label :image6 %><br>
    <%= f.file_field :image6 %>
  </p>


  <p>
    <%= f.submit "Save" %>
  </p>
  </div>
<% end %>

app/views/listings/show.html.erb
<!-- <div class="title-info">
<%= link_to "Back to Listings", listings_url %> | <%= link_to "Edit", edit_listing_path(@listing) %> | <%= link_to "Delete", @listing, method: :delete, data: {confirm: "Are you sure you want to delete this listing?"}  %>


 -->

<!-- ABOVE NEEDS TO BE MOVED TO HEADER! -->

<div class="address">
	<p><%= @listing.address %></p>
</div>
<div class="price-agent">
	<p>$<%= @listing.price %> | <%= @listing.agent %> | <%= @listing.city %></p>
</div>


<div class="image-duo">
<img src="<%= @listing.image.url %>" align="middle"><img class="img2" src="<%= @listing.image2.url %>" align="middle">
</div>

<div class="image-duo">
<img src="<%= @listing.image3.url %>" align="middle"><img class="img2" src="<%= @listing.image4.url %>" align="middle">
</div>

<div class="image-duo">
<img src="<%= @listing.image5.url %>" align="middle"><img class="img2" src="<%= @listing.image6.url %>" align="middle">
</div>


<br>
<div class="listing-info">
	 <p>Bedrooms: <%= @listing.bedrooms %></p>
	 <p>Bathrooms: <%= @listing.bathrooms %></p>
	 <p>Square Footage: <%= @listing.sqft %></p>
	 <p>About <%= @listing.address %></p><p><%= @listing.description%></p>
	 <p>Agent: <%= @listing.agent %></p>
	 <p>Email: <%= @listing.email %></p>
	 <p>Website: <%= @listing.website %></p>
	 <p>Contact: <%= @listing.number %></p>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :firstname %><br/>
    <%= f.text_field :firstname %>
  </div>

    <div class="field">
    <%= f.label :lastname %><br/>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>